#' Embedding Plot Using the JavaScript Library Plotly
#'
#' Plots the embedded coordinates, with each point colored by a specified
#' color, using Plotly.
#'
#' This will open a web browser if you are using the R CLI. In RStudio, it
#' will put the plot in RStudio's Plots tab.
#'
#' More information on plotly is available at its website,
#' <https://plotly.com/r/>.
#'
#' The `x` argument can be used to provide a suitable vector of colors
#' from either a data frame or vector.
#'
#' If a data frame is provided, then a vector of colors will be looked for. If
#' it's present, it will be used as the `colors` argument directly.
#' Otherwise, a factor column will be looked for, and each level will be mapped
#' to a different color. Otherwise, one color will be used for each point. If
#' more than one column of a type is found in the data frame, the last one
#' encountered is used.
#'
#' If a vector is provided, a similar procedure to the data frame is used when
#' mapping from its content to a vector of colors. Additionally, a numeric vector
#' can be provided, which will be linearly mapped to a color scheme.
#'
#' The `color_scheme` parameter can be one of:
#'
#' - A palette function that takes an integer `n` and returns a vector of colors,
#'   e.g. [grDevices::rainbow()]. For some other applicable functions, see the
#'   `Palettes` help page in the `grDevices` package (e.g. by running the
#'   `?rainbow` command).
#' - A vector of colors making up a custom color scheme of your own devising,
#'   e.g. `c("red", "green", "blue")`. There must be at least two colors in the
#'   list.
#' - The name of a color scheme provided by the
#'   [paletteer](https://cran.r-project.org/package=paletteer) package, in the
#'   form `"package::palette"`. Some examples include
#'   `"dutchmasters::milkmaid"`, `"cartography::green.pal"`,
#'   `"viridis::inferno"` and `"RColorBrewer::Dark2"`. If more colors are
#'   required than supported by the color scheme, interpolation will be used to
#'   create the required number of colors.
#'
#' The default for a numeric scale is to use [grDevices::rainbow()]
#' and for factor columns to use a palette generated by
#' [Polychrome::createPalette()].
#'
#' @param coords Matrix of embedded coordinates, with as many rows as
#'   observations, and 2 columns.
#' @param x Either a data frame or a column that can be used to derive a
#'   suitable vector of colors. Ignored if `colors` is provided.
#' @param colors Vector containing colors for each coordinate.
#' @param color_scheme A color scheme. See Details. Ignored if `colors`
#'   is specified.
#' @param num_colors Number of distinct colors to use in the palette, when
#'   `x` is a numeric vector, on the assumption that the palette is continuous
#'   (which it probably should be). Ignored if `x` is not a numeric vector. If
#'   set to `NULL`, it will be set to `length(x)`.
#' @param alpha_scale Scale the opacity alpha of the colors, between 0 and 1.
#'   Useful for increasing the transparency of points, especially with large
#'   plots with lots of overlap.
#' @param limits The range that the colors should map over when mapping from a
#'  numeric vector. If not specified, then the range of `x`. This is useful
#'  if there is some external absolute scale that should be used. Ignored if
#'  `x` is not a numeric vector.
#' @param clip_limit_values If `TRUE` (the default) and `limits` is provided,
#'   then any value that lies outside the `limits` is clipped to the limiting
#'   values. If `tooltip = NULL` then the original values will be preserved in
#'   the tooltip. If `clip_limit_values = FALSE`, then values outside the
#'   `limits` will be shown in the "missing" color.
#' @param cex Size of the points. Ignored if `text` is provided.
#' @param text Vector of label text to display instead of a point. If the labels
#'   are long or the data set is large, this is unlikely to be very legible, but
#'   is occasionally useful.
#' @param tooltip Vector of tooltip text, to be displayed when a point is
#'   hovered over.
#' @param title Title for the plot.
#' @param show_legend If `TRUE`, display a legend. Ignored unless a
#'   suitable categorical value is provided as `x` (or one can be found).
#' @param equal_axes If `TRUE`, the X and Y axes are set to have the
#'   same extents.
#' @param pc_axes If `TRUE`, the `coords` are replaced by the
#'   first two (unscaled) principal components, which should have the effect of
#'   rotating the data (with a potential reflection) so the main variance aligns
#'   along the X-axis. Should not have any other scaling effect.
#' @param xlim Vector of two numeric values to give the numeric extent of the
#'   X-axis. Ignored if `equal_axes = TRUE` or `pc_axes = TRUE`.
#' @param ylim Vector of two numeric values to give the numeric extent of the
#'   Y-axis. Ignored if `equal_axes = TRUE` or `pc_axes = TRUE`.
#' @param rev logical indicating whether the ordering of the colors should be
#'   reversed.
#' @param verbose If `TRUE`, log messages to the console, mainly when
#'   searching for a suitable color column in a dataframe.
#' @export
#' @examplesIf interactive()
#' # Embed with PCA
#' pca_iris <- stats::prcomp(iris[, -5], retx = TRUE, rank. = 2)
#'
#' # Load the plotly package
#' library("plotly")
#'
#' # Visualize the resulting embedding, colored by iris species, using the
#' # rainbow color scheme
#' embed_plotly(pca_iris$x, iris$Species,
#'   color_scheme = rainbow,
#'   title = "iris PCA"
#' )
#'
#' # topo.colors scheme
#' embed_plotly(pca_iris$x, iris$Species, color_scheme = topo.colors)
#'
#' # Pass in data frame and it will use the last (in this case, only) factor
#' # column it finds
#' embed_plotly(pca_iris$x, iris)
#'
#' # Don't have to see a legend if the tooltips will do
#' embed_plotly(pca_iris$x, iris, show_legend = FALSE)
#'
#' # Custom tooltips
#' embed_plotly(pca_iris$x, iris, tooltip = paste("Species:", iris$Species))
#'
#' # Use the "Dark2" RColorBrewer scheme
#' embed_plotly(pca_iris$x, iris, color_scheme = "RColorBrewer::Dark2")
#'
#' # Can plot the category names instead of points, but looks bad if they're
#' # long (or the dataset is large)
#' embed_plotly(pca_iris$x, iris$Species, cex = 0.5, text = iris$Species)
#'
#' # Visualize numeric value (petal length) as a color
#' embed_plotly(pca_iris$x, iris$Petal.Length, color_scheme = "RColorBrewer::Blues")
#'
#' # Can force axes to be equal size to stop cluster being distorted in one
#' # direction
#' embed_plotly(pca_iris$x, iris$Petal.Length,
#'   color_scheme = "RColorBrewer::Blues",
#'   equal_axes = TRUE
#' )
embed_plotly <- function(
  coords,
  x = NULL,
  colors = NULL,
  color_scheme = NULL,
  num_colors = 15,
  alpha_scale = 1,
  limits = NULL,
  clip_limit_values = TRUE,
  title = NULL,
  show_legend = TRUE,
  cex = 1,
  text = NULL,
  tooltip = NULL,
  equal_axes = FALSE,
  pc_axes = FALSE,
  xlim = NULL,
  ylim = NULL,
  rev = FALSE,
  verbose = FALSE
) {
  if (!requireNamespace("plotly", quietly = TRUE)) {
    stop(
      "Package \"plotly\" must be installed to use embed_plotly().",
      call. = FALSE
    )
  }

  validate_logical_scalar(clip_limit_values, "'clip_limit_values'")
  validate_logical_scalar(show_legend, "'show_legend'")
  validate_logical_scalar(equal_axes, "'equal_axes'")
  validate_logical_scalar(pc_axes, "'pc_axes'")
  validate_logical_scalar(rev, "'rev'")
  validate_logical_scalar(verbose, "'verbose'")
  validate_alpha_scale(alpha_scale)
  validate_cex(cex)
  if (!is.null(xlim)) {
    validate_numeric_limits(xlim)
  }
  if (!is.null(ylim)) {
    validate_numeric_limits(ylim)
  }
  coords <- validate_coords(coords, pc_axes = pc_axes)
  n <- nrow(coords)
  if (!is.null(text)) {
    text <- recycle_input(text, n, "'text'")
  }
  if (!is.null(tooltip)) {
    tooltip <- recycle_input(tooltip, n, "'tooltip'")
  }
  color_res <- resolve_colors(
    x = x,
    colors = colors,
    n = n,
    color_scheme = color_scheme,
    num_colors = num_colors,
    limits = limits,
    alpha_scale = alpha_scale,
    rev = rev,
    verbose = verbose,
    clip_limit_values = clip_limit_values
  )

  if (pc_axes) {
    coords <- pc_rotate(coords)
  }

  if (equal_axes) {
    lims <- base::range(coords)
    xlim <- lims
    ylim <- lims
  }

  rows <- which(color_res$keep)
  labels <- color_res$labels
  hover_text <- plotly_hover_text(
    n = length(rows),
    row_ids = rows,
    tooltip = if (is.null(tooltip)) NULL else tooltip[rows],
    text = if (is.null(text)) NULL else text[rows],
    labels = if (is.null(labels)) NULL else labels[rows]
  )

  if (color_res$kind == "discrete") {
    p <- plotly::plot_ly(
      x = coords[rows, 1],
      y = coords[rows, 2],
      color = ~labels,
      colors = color_res$palette,
      type = "scatter",
      mode = if (is.null(text)) "markers" else "text",
      text = if (is.null(text)) hover_text else text[rows],
      hovertext = hover_text,
      hoverinfo = "text",
      marker = if (is.null(text)) {
        list(size = cex * 6, opacity = alpha_scale)
      } else {
        NULL
      }
    )
    layout_show_legend <- show_legend
  } else if (color_res$kind == "continuous") {
    marker <- list(
      size = cex * 6,
      opacity = alpha_scale,
      color = color_res$mapped_values[rows],
      colorscale = plotly_colorscale(color_res$palette),
      showscale = show_legend
    )
    if (!is.null(color_res$limits)) {
      marker$cmin <- color_res$limits[1]
      marker$cmax <- color_res$limits[2]
    }
    if (show_legend) {
      marker$colorbar <- list(title = "")
    }
    p <- plotly::plot_ly(
      x = coords[rows, 1],
      y = coords[rows, 2],
      type = "scatter",
      mode = if (is.null(text)) "markers" else "text",
      text = if (is.null(text)) hover_text else text[rows],
      hovertext = hover_text,
      hoverinfo = "text",
      marker = if (is.null(text)) marker else NULL,
      textfont = if (is.null(text)) NULL else
        list(color = color_res$colors[rows])
    )
    layout_show_legend <- FALSE
  } else {
    if (!is.null(text)) {
      p <- plotly::plot_ly(
        x = coords[rows, 1],
        y = coords[rows, 2],
        type = "scatter",
        mode = "text",
        text = text[rows],
        hovertext = hover_text,
        hoverinfo = "text",
        textfont = list(color = color_res$colors[rows])
      )
    } else {
      p <- plotly::plot_ly(
        x = coords[rows, 1],
        y = coords[rows, 2],
        type = "scatter",
        mode = "markers",
        text = hover_text,
        hovertext = hover_text,
        hoverinfo = "text",
        marker = list(
          size = cex * 6,
          opacity = alpha_scale,
          color = color_res$colors[rows]
        )
      )
    }
    layout_show_legend <- FALSE
  }
  p <-
    plotly::layout(
      p,
      title = title,
      xaxis = list(
        title = "X",
        zeroline = FALSE,
        showline = TRUE,
        showgrid = FALSE,
        range = xlim
      ),
      yaxis = list(
        title = "Y",
        zeroline = FALSE,
        showline = TRUE,
        showgrid = FALSE,
        range = ylim
      ),
      showlegend = layout_show_legend
    )
  p
}

plotly_colorscale <- function(colors) {
  if (length(colors) == 1) {
    colors <- rep(colors, 2)
  }
  stops <- seq(0, 1, length.out = length(colors))
  unname(Map(function(stop, color) list(stop, color), stops, colors))
}

plotly_numeric_limits <- function(x, limits = NULL) {
  if (!is.null(limits)) {
    return(validate_numeric_limits(limits))
  }

  finite_x <- x[is.finite(x)]
  if (length(finite_x) == 0) {
    return(NULL)
  }
  range(finite_x)
}

plotly_hover_text <- function(
  n,
  row_ids = seq_len(n),
  tooltip = NULL,
  text = NULL,
  labels = NULL
) {
  if (!is.null(tooltip)) {
    hover <- tooltip
  } else if (!is.null(text)) {
    hover <- text
  } else if (!is.null(labels)) {
    hover <- labels
  } else {
    hover <- rep("", n)
  }

  paste0(as.character(row_ids), ": ", hover)
}
