#' Embedding Plot Using the JavaScript Library Plotly
#'
#' Plots the embedded coordinates, with each point colored by a specified
#' color, using Plotly.
#'
#' This will open a web browser if you are using the R CLI. In RStudio, it
#' will put the plot in RStudio's Plots tab.
#'
#' More information on plotly is available at its website,
#' <https://plotly.com/r/>.
#'
#' The `x` argument can be used to provide a suitable vector of colors
#' from either a data frame or vector.
#'
#' If a data frame is provided, then a vector of colors will be looked for. If
#' it's present, it will be used as the `colors` argument directly.
#' Otherwise, a factor column will be looked for, and each level will be mapped
#' to a different color. Otherwise, one color will be used for each point. If
#' more than one column of a type is found in the data frame, the last one
#' encountered is used.
#'
#' If a vector is provided, a similar procedure to the data frame is used when
#' mapping from its content to a vector of colors. Additionally, a numeric vector
#' can be provided, which will be linearly mapped to a color scheme.
#'
#' The `color_scheme` parameter can be one of:
#'
#' - A palette function that takes an integer `n` and returns a vector of colors,
#'   e.g. [grDevices::rainbow()]. For some other applicable functions, see the
#'   `Palettes` help page in the `grDevices` package (e.g. by running the
#'   `?rainbow` command).
#' - A vector of colors making up a custom color scheme of your own devising,
#'   e.g. `c("red", "green", "blue")`. There must be at least two colors in the
#'   list.
#' - The name of a color scheme provided by the
#'   [paletteer](https://cran.r-project.org/package=paletteer) package, in the
#'   form `"package::palette"`. Some examples include
#'   `"dutchmasters::milkmaid"`, `"cartography::green.pal"`,
#'   `"viridis::inferno"` and `"RColorBrewer::Dark2"`. If more colors are
#'   required than supported by the color scheme, interpolation will be used to
#'   create the required number of colors.
#'
#' The default for a numeric scale is to use [grDevices::rainbow()]
#' and for factor columns to use a palette generated by
#' [Polychrome::createPalette()].
#'
#' @param coords Matrix of embedded coordinates, with as many rows as
#'   observations, and 2 columns.
#' @param x Either a data frame or a column that can be used to derive a
#'   suitable vector of colors. Ignored if `colors` is provided.
#' @param colors Vector containing colors for each coordinate.
#' @param color_scheme A color scheme. See Details. Ignored if `colors`
#'   is specified.
#' @param num_colors Number of distinct colors to use in the palette, when
#'   `x` is a numeric vector, on the assumption that the palette is continuous
#'   (which it probably should be). Ignored if `x` is not a numeric vector. If
#'   set to `NULL`, it will be set to `length(x)`.
#' @param alpha_scale Scale the opacity alpha of the colors, between 0 and 1.
#'   Useful for increasing the transparency of points, especially with large
#'   plots with lots of overlap.
#' @param limits The range that the colors should map over when mapping from a
#'  numeric vector. If not specified, then the range of `x`. This is useful
#'  if there is some external absolute scale that should be used. Ignored if
#'  `x` is not a numeric vector.
#' @param clip_limit_values If `TRUE` (the default) and `limits` is provided,
#'   then any value that lies outside the `limits` is clipped to the limiting
#'   values. If `tooltip = NULL` then the original values will be preserved in
#'   the tooltip. If `clip_limit_values = FALSE`, then values outside the
#'   `limits` will be shown in the "missing" color.
#' @param cex Size of the points. Ignored if `text` is provided.
#' @param text Vector of label text to display instead of a point. If the labels
#'   are long or the data set is large, this is unlikely to be very legible, but
#'   is occasionally useful.
#' @param tooltip Vector of tooltip text, to be displayed when a point is
#'   hovered over.
#' @param title Title for the plot.
#' @param show_legend If `TRUE`, display a legend. Ignored unless a
#'   suitable categorical value is provided as `x` (or one can be found).
#' @param equal_axes If `TRUE`, the X and Y axes are set to have the
#'   same extents.
#' @param pc_axes If `TRUE`, the `coords` are replaced by the
#'   first two (unscaled) principal components, which should have the effect of
#'   rotating the data (with a potential reflection) so the main variance aligns
#'   along the X-axis. Should not have any other scaling effect.
#' @param xlim Vector of two numeric values to give the numeric extent of the
#'   X-axis. Ignored if `equal_axes = TRUE` or `pc_axes = TRUE`.
#' @param ylim Vector of two numeric values to give the numeric extent of the
#'   Y-axis. Ignored if `equal_axes = TRUE` or `pc_axes = TRUE`.
#' @param rev logical indicating whether the ordering of the colors should be
#'   reversed.
#' @param verbose If `TRUE`, log messages to the console, mainly when
#'   searching for a suitable color column in a dataframe.
#' @export
#' @examplesIf interactive()
#' # Embed with PCA
#' pca_iris <- stats::prcomp(iris[, -5], retx = TRUE, rank. = 2)
#'
#' # Load the plotly package
#' library("plotly")
#'
#' # Visualize the resulting embedding, colored by iris species, using the
#' # rainbow color scheme
#' embed_plotly(pca_iris$x, iris$Species,
#'   color_scheme = rainbow,
#'   title = "iris PCA"
#' )
#'
#' # topo.colors scheme
#' embed_plotly(pca_iris$x, iris$Species, color_scheme = topo.colors)
#'
#' # Pass in data frame and it will use the last (in this case, only) factor
#' # column it finds
#' embed_plotly(pca_iris$x, iris)
#'
#' # Don't have to see a legend if the tooltips will do
#' embed_plotly(pca_iris$x, iris, show_legend = FALSE)
#'
#' # Custom tooltips
#' embed_plotly(pca_iris$x, iris, tooltip = paste("Species:", iris$Species))
#'
#' # Use the "Dark2" RColorBrewer scheme
#' embed_plotly(pca_iris$x, iris, color_scheme = "RColorBrewer::Dark2")
#'
#' # Can plot the category names instead of points, but looks bad if they're
#' # long (or the dataset is large)
#' embed_plotly(pca_iris$x, iris$Species, cex = 0.5, text = iris$Species)
#'
#' # Visualize numeric value (petal length) as a color
#' embed_plotly(pca_iris$x, iris$Petal.Length, color_scheme = "RColorBrewer::Blues")
#'
#' # Can force axes to be equal size to stop cluster being distorted in one
#' # direction
#' embed_plotly(pca_iris$x, iris$Petal.Length,
#'   color_scheme = "RColorBrewer::Blues",
#'   equal_axes = TRUE
#' )
embed_plotly <- function(
  coords,
  x = NULL,
  colors = NULL,
  color_scheme = NULL,
  num_colors = 15,
  alpha_scale = 1,
  limits = NULL,
  clip_limit_values = TRUE,
  title = NULL,
  show_legend = TRUE,
  cex = 1,
  text = NULL,
  tooltip = NULL,
  equal_axes = FALSE,
  pc_axes = FALSE,
  xlim = NULL,
  ylim = NULL,
  rev = FALSE,
  verbose = FALSE
) {
  if (!requireNamespace("plotly", quietly = TRUE)) {
    stop(
      "Package \"plotly\" must be installed to use embed_plotly().",
      call. = FALSE
    )
  }

  if (methods::is(coords, "list") && !is.null(coords$coords)) {
    coords <- coords$coords
  }

  mode <- if (is.null(text)) "markers" else "text"
  labels <- NULL
  trace_type <- "direct"
  numeric_values <- NULL
  numeric_tooltip <- NULL

  if (is.null(colors)) {
    if (!is.null(x)) {
      if (methods::is(x, "numeric")) {
        trace_type <- "numeric"
        labels <- x
        numeric_values <- x
        color_limits <- plotly_numeric_limits(numeric_values, limits)
        if (!is.null(color_limits)) {
          below_limits <- numeric_values < color_limits[1]
          above_limits <- numeric_values > color_limits[2]
          outside_limits <- is.finite(numeric_values) &
            (below_limits | above_limits)

          if (clip_limit_values) {
            if (any(outside_limits) && is.null(tooltip)) {
              numeric_tooltip <- labels
            }
            numeric_values[numeric_values > color_limits[2]] <- color_limits[2]
            numeric_values[numeric_values < color_limits[1]] <- color_limits[1]
          } else {
            numeric_values[outside_limits] <- NA_real_
          }
        }

        numeric_values[!is.finite(numeric_values)] <- NA_real_
        mode <- "markers"
        if (is.null(num_colors)) {
          num_colors <- length(x)
        }
        if (is.null(color_scheme)) {
          color_scheme <- grDevices::rainbow
        }
        colors <- make_palette(
          ncolors = max(1, num_colors),
          color_scheme = color_scheme
        )
      } else {
        res <- color_helper(x, color_scheme = color_scheme, verbose = verbose)
        if (!is.null(res$labels)) {
          trace_type <- "categorical"
          labels <- res$labels
          colors <- res$palette
        } else {
          colors <- res$colors
        }
      }
    } else {
      # one color per point
      colors <- make_palette(
        ncolors = nrow(coords),
        color_scheme = color_scheme,
        verbose = verbose
      )
      show_legend <- FALSE
    }
  } else if (is.null(text)) {
    labels <- colors
  }
  if (rev) {
    colors <- rev(colors)
  }

  if (pc_axes) {
    coords <- pc_rotate(coords)
  }

  if (equal_axes) {
    lims <- base::range(coords)
    xlim <- lims
    ylim <- lims
  }

  hover_text <- plotly_hover_text(
    n = nrow(coords),
    tooltip = tooltip,
    text = text,
    labels = labels,
    numeric_tooltip = numeric_tooltip
  )

  if (trace_type == "categorical") {
    p <- plotly::plot_ly(
      x = coords[, 1],
      y = coords[, 2],
      color = ~labels,
      colors = colors,
      type = "scatter",
      mode = mode,
      text = if (mode == "text") text else hover_text,
      hovertext = hover_text,
      hoverinfo = "text",
      marker = if (mode == "markers") {
        list(size = cex * 6, opacity = alpha_scale)
      } else {
        NULL
      }
    )
    layout_show_legend <- show_legend
  } else if (trace_type == "numeric") {
    marker <- list(
      size = cex * 6,
      opacity = alpha_scale,
      color = numeric_values,
      colorscale = plotly_colorscale(colors),
      showscale = show_legend
    )
    if (!is.null(color_limits)) {
      marker$cmin <- color_limits[1]
      marker$cmax <- color_limits[2]
    }
    if (show_legend) {
      marker$colorbar <- list(title = "")
    }
    p <- plotly::plot_ly(
      x = coords[, 1],
      y = coords[, 2],
      type = "scatter",
      mode = mode,
      text = hover_text,
      hovertext = hover_text,
      hoverinfo = "text",
      marker = marker
    )
    layout_show_legend <- FALSE
  } else {
    if (mode == "text") {
      p <- plotly::plot_ly(
        x = coords[, 1],
        y = coords[, 2],
        type = "scatter",
        mode = mode,
        text = text,
        hovertext = hover_text,
        hoverinfo = "text",
        textfont = list(color = colors)
      )
    } else {
      p <- plotly::plot_ly(
        x = coords[, 1],
        y = coords[, 2],
        type = "scatter",
        mode = mode,
        text = hover_text,
        hovertext = hover_text,
        hoverinfo = "text",
        marker = list(
          size = cex * 6,
          opacity = alpha_scale,
          color = colors
        )
      )
    }
    layout_show_legend <- FALSE
  }
  p <-
    plotly::layout(
      p,
      title = title,
      xaxis = list(
        title = "X",
        zeroline = FALSE,
        showline = TRUE,
        showgrid = FALSE,
        range = xlim
      ),
      yaxis = list(
        title = "Y",
        zeroline = FALSE,
        showline = TRUE,
        showgrid = FALSE,
        range = ylim
      ),
      showlegend = layout_show_legend
    )
  p
}

plotly_colorscale <- function(colors) {
  if (length(colors) == 1) {
    colors <- rep(colors, 2)
  }
  stops <- seq(0, 1, length.out = length(colors))
  unname(Map(function(stop, color) list(stop, color), stops, colors))
}

plotly_numeric_limits <- function(x, limits = NULL) {
  if (!is.null(limits)) {
    return(validate_numeric_limits(limits))
  }

  finite_x <- x[is.finite(x)]
  if (length(finite_x) == 0) {
    return(NULL)
  }
  range(finite_x)
}

plotly_hover_text <- function(
  n,
  tooltip = NULL,
  text = NULL,
  labels = NULL,
  numeric_tooltip = NULL
) {
  if (!is.null(tooltip)) {
    hover <- tooltip
  } else if (!is.null(numeric_tooltip)) {
    hover <- numeric_tooltip
  } else if (!is.null(text)) {
    hover <- text
  } else if (!is.null(labels)) {
    hover <- labels
  } else {
    hover <- rep("", n)
  }

  paste0(as.character(seq_along(hover)), ": ", hover)
}
